name: time-bandits
version: 0.1.0.0
license: Apache-2.0
author: Sam Hart
maintainer: sam@timewave.computer
copyright: 2025 Sam Hart

dependencies:
  - base >= 4.18 && < 5
  - containers
  - text
  - bytestring
  - mtl
  - aeson
  - polysemy
  - polysemy-plugin
  - polysemy-log
  - relude

library:
  source-dirs: src

tests:
  time-bandits-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - time-bandits
      - containers
      - text
      - bytestring
      - mtl
      - hspec >= 2.8.0
      - hspec-discover >= 2.8.0
      - QuickCheck >= 2.14.0
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N 