[[rules]]
rule_id = "eth-balance-observation-1"
fact_type = "BalanceObservation"
proof = "StateProof"
enabled = true
description = "Observes ETH balance changes for a specific address"

path.source = "ethereum"
path.selector = "account.balance"

[path.parameters]
address = "0x742d35Cc6634C0532925a3b844Bc454e4438f44e"
network = "mainnet"

[[conditions]]
field = "balance"
operator = ">"
value = 1000000000000000000  # 1 ETH in wei

[[conditions]]
check_field = "last_updated"

[metadata]
version = "1.0.0"
author = "Time Bandits Team"
created_at = "2024-06-01" 